# -*- coding: utf-8 -*-
"""1_json_to_nparray.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JT1I1turp0tWejpjUvyFXYZ6zQDMBhaj
"""

import numpy as np

json = {
        "lines": [
            {
                "points": [
                    {
                        "x": 202,
                        "y": 106
                    },
                    {
                        "x": 202,
                        "y": 106
                    },
                    {
                        "x": 197.41864013671875,
                        "y": 94.62796020507812
                    },
                    {
                        "x": 195.14295959472656,
                        "y": 89.57159423828125
                    },
                    {
                        "x": 188.97906494140625,
                        "y": 86.93978881835938
                    },
                    {
                        "x": 175.8347930908203,
                        "y": 86
                    },
                    {
                        "x": 158.7085723876953,
                        "y": 86.81243896484376
                    },
                    {
                        "x": 143.00350952148438,
                        "y": 90.36502075195312
                    },
                    {
                        "x": 127.55096435546875,
                        "y": 96.8428955078125
                    },
                    {
                        "x": 114.42387390136719,
                        "y": 104.81979370117188
                    },
                    {
                        "x": 103.7425537109375,
                        "y": 118.26242065429688
                    },
                    {
                        "x": 97.0250244140625,
                        "y": 132.18743896484375
                    },
                    {
                        "x": 93.06036376953125,
                        "y": 147.78872680664062
                    },
                    {
                        "x": 91,
                        "y": 163.92556762695312
                    },
                    {
                        "x": 92.23541259765625,
                        "y": 179.7666015625
                    },
                    {
                        "x": 96.36880493164062,
                        "y": 195.69387817382812
                    },
                    {
                        "x": 101.56135559082031,
                        "y": 208.759521484375
                    },
                    {
                        "x": 111.1419677734375,
                        "y": 221.7845458984375
                    },
                    {
                        "x": 125.09393310546875,
                        "y": 233.47515869140625
                    },
                    {
                        "x": 140.3177947998047,
                        "y": 238.53680419921875
                    },
                    {
                        "x": 159.0948028564453,
                        "y": 241.8994140625
                    },
                    {
                        "x": 180.83602905273438,
                        "y": 239.60580444335938
                    },
                    {
                        "x": 202.18667602539062,
                        "y": 234.23880004882812
                    },
                    {
                        "x": 219.06015014648438,
                        "y": 225.917724609375
                    },
                    {
                        "x": 234.775390625,
                        "y": 212.09466552734375
                    },
                    {
                        "x": 244.81231689453125,
                        "y": 197.10031127929688
                    },
                    {
                        "x": 253.03335571289062,
                        "y": 178.60366821289062
                    },
                    {
                        "x": 256.0041809082031,
                        "y": 158.30679321289062
                    },
                    {
                        "x": 255.33486938476562,
                        "y": 138.03256225585938
                    },
                    {
                        "x": 249.4937744140625,
                        "y": 120.31362915039062
                    },
                    {
                        "x": 237.70309448242188,
                        "y": 103.38632202148438
                    },
                    {
                        "x": 216.12193298339844,
                        "y": 86.70779418945312
                    },
                    {
                        "x": 187.10755920410156,
                        "y": 76.6822509765625
                    },
                    {
                        "x": 163.5,
                        "y": 76.5
                    },
                    {
                        "x": 163.5,
                        "y": 76.5
                    }
                ],
                "brushColor": "#fff",
                "brushRadius": 2
            },
            {
                "points": [
                    {
                        "x": 262.5,
                        "y": 378.5
                    },
                    {
                        "x": 262.5,
                        "y": 378.5
                    },
                    {
                        "x": 257.00323486328125,
                        "y": 363.51287841796875
                    },
                    {
                        "x": 253.6265869140625,
                        "y": 348.25738525390625
                    },
                    {
                        "x": 248.45248413085938,
                        "y": 326.3719482421875
                    },
                    {
                        "x": 243.97598266601562,
                        "y": 303.8798828125
                    },
                    {
                        "x": 240.16061401367188,
                        "y": 283.2181701660156
                    },
                    {
                        "x": 234.50375366210938,
                        "y": 259.0977783203125
                    },
                    {
                        "x": 231.36895751953125,
                        "y": 223.24798583984375
                    },
                    {
                        "x": 229.36917114257812,
                        "y": 196.86468505859375
                    },
                    {
                        "x": 229,
                        "y": 169.90512084960938
                    },
                    {
                        "x": 229.56210327148438,
                        "y": 147.31991577148438
                    },
                    {
                        "x": 229.5,
                        "y": 132.38064575195312
                    },
                    {
                        "x": 229.5,
                        "y": 128.5
                    },
                    {
                        "x": 229.5,
                        "y": 128.5
                    }
                ],
                "brushColor": "#fff",
                "brushRadius": 2
            }
        ],
        "width": 300,
        "height": 400
    }

x_values = []
y_values = []
x_y_values = []
for value in json['lines']:
    for val in value["points"]:
        x_values.append(round(val['x']))
        y_values.append(round(val['y']))
        x_y_values.append([round(val['x']),round(val['y'])])

max_x = max(x_values)

max_y = max(y_values)

convert_matrix = np.zeros(shape=(max_x+1,max_y+1))
for value in x_y_values:
    convert_matrix[value[0]][value[1]] = 1

#convert matrix = 1's at (x,y) cordinates
print(convert_matrix)

convert_matrix_copy = convert_matrix.copy()
for row_index in range(len(convert_matrix_copy)):
    count_one = 0
    index_one = []
    for element_index in range(0,len(convert_matrix_copy[row_index])-1):
        if(convert_matrix_copy[row_index][element_index] == 1):
            index_one.append(element_index)
            count_one += 1
        if(count_one > 1):
            start_index = index_one[0]
            end_index = index_one[len(index_one)-1]
            for i in range(start_index,end_index):
                convert_matrix_copy[row_index][i] = 1

#convert matrix copy = 1's at (x,y) cordinates + 1's inside the region selected
print(convert_matrix_copy)

peri_1 = np.count_nonzero(convert_matrix == 1.0)
print(peri_1)
area_1 = np.count_nonzero(convert_matrix_copy == 1.0)
print(area_1)